[project]
name = "standard-rag-project"
version = "0.1.0"
description = "A standard RAG implementation with BM25, ChromaDB, RRF, and Cross-Encoder reranking."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "uvicorn",
    "langchain",
    "langchain-community",
    "langchain-chroma",
    "chromadb",
    "rank_bm25",
    "sentence-transformers",
    "pypdf",
    "python-dotenv",
    "pydantic",
    "pydantic-settings",
    "python-multipart",
    "streamlit",
    "requests"
]

